# -*- coding: utf-8 -*-
"""joongbunews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ndCKgMK_4JgY7J1sAApvJzNJcQ1_YBXU
"""

import requests
import datetime

# ===== [설정] =====
KEYWORDS = ["광선로 단선", "광케이블 단선", "충청", "충남", "충북", "대전", "세종", "강원"]  # 원하는 키워드로 수정
TOKEN = "7850330463:AAFQ7gjUc4tNp1Tv68YDUDc-e6oS5fDUf4c"           # 텔레그램 봇 토큰
CHAT_ID = "7737652316"                                             # 텔레그램 채팅 ID

# 네이버 API 인증 정보 (반드시 본인 정보로 변경)
NAVER_CLIENT_ID = "E8O90EX19G9rVFg6SyFY"
NAVER_CLIENT_SECRET = "ChywCbWRGX"

# ===== [1] 네이버 뉴스 API 함수 =====
def crawl_naver_news(keywords):
    print("🟢 [NAVER] 뉴스 API로 수집 중...")
    results = []
    url = "https://openapi.naver.com/v1/search/news.json"
    headers = {
        "X-Naver-Client-Id": NAVER_CLIENT_ID,
        "X-Naver-Client-Secret": NAVER_CLIENT_SECRET
    }
    for keyword in keywords:
        params = {
            "query": keyword,
            "display": 3,  # 키워드당 3건
            "sort": "date"
        }
        res = requests.get(url, headers=headers, params=params)
        if res.status_code == 200:
            items = res.json().get("items", [])
            for item in items:
                # HTML 태그 제거
                import re
                title = re.sub('<.*?>', '', item.get("title", ""))
                link = item.get("link", "")
                results.append(f"[{keyword}] {title}\n{link}")
        else:
            print(f"❌ 네이버 API 호출 실패: {res.status_code} ({keyword})")
    return results

# ===== [2] 텔레그램 전송 함수 =====
def send_telegram_message(message: str, token: str, chat_id: str):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = {
        "chat_id": chat_id,
        "text": message
    }
    response = requests.post(url, data=data)
    if response.status_code == 200:
        print("✅ 텔레그램 메시지 전송 성공")
    else:
        print(f"❌ 텔레그램 메시지 전송 실패: {response.status_code}")

# ===== [3] 실행 함수 =====
def run():
    print(f"📅 [{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 뉴스 수집 시작")
    news = crawl_naver_news(KEYWORDS)

    if news:
        message = f"📰 오늘의 뉴스 요약 ({len(news)}건):\n\n" + "\n\n".join(news)
        send_telegram_message(message, TOKEN, CHAT_ID)
    else:
        print("📭 수집된 뉴스가 없습니다.")

# ===== [4] 실행 =====
if __name__ == "__main__":
    run()