# -*- coding: utf-8 -*-
"""newstest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9gbUgry0Ncy0APDWv2psOUVegZnXg6X
"""

import requests
import datetime
import re

# ===== [설정] =====
REGIONS = ["충청", "충남", "충북", "대전", "세종", "강원"]
FAULTS = ["사전투표"]
TOKEN = "7850330463:AAFQ7gjUc4tNp1Tv68YDUDc-e6oS5fDUf4c"
CHAT_ID = "-4784405371"

NAVER_CLIENT_ID = "E8O90EX19G9rVFg6SyFY"
NAVER_CLIENT_SECRET = "ChywCbWRGX"

# ===== [1] 네이버 뉴스 API 함수 =====
def crawl_naver_news(keywords):
    print("🟢 [NAVER] 뉴스 API로 수집 중...")
    results = []
    url = "https://openapi.naver.com/v1/search/news.json"
    headers = {
        "X-Naver-Client-Id": NAVER_CLIENT_ID,
        "X-Naver-Client-Secret": NAVER_CLIENT_SECRET
    }
    for keyword in keywords:
        params = {
            "query": keyword,
            "display": 10,
            "sort": "date"
        }
        res = requests.get(url, headers=headers, params=params)
        if res.status_code == 200:
            items = res.json().get("items", [])
            for item in items:
                title = re.sub('<.*?>', '', item.get("title", ""))
                desc = re.sub('<.*?>', '', item.get("description", ""))
                link = item.get("link", "")
                results.append({
                    "title": title,
                    "desc": desc,
                    "link": link
                })
        else:
            print(f"❌ 네이버 API 호출 실패: {res.status_code} ({keyword})")
    return results

# ===== [2] AND 조건 필터링 함수 =====
def filter_news_and(news, regions, faults):
    filtered = []
    for n in news:
        content = n["title"] + " " + n["desc"]
        for region in regions:
            for fault in faults:
                if region in content and fault in content:
                    filtered.append(f"[{region}+{fault}] {n['title']}\n{n['link']}")
    return list(set(filtered))  # 중복 제거

# ===== [3] 텔레그램 전송 함수 =====
def send_telegram_message(message: str, token: str, chat_id: str):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = {
        "chat_id": chat_id,
        "text": message
    }
    response = requests.post(url, data=data)
    if response.status_code == 200:
        print("✅ 텔레그램 메시지 전송 성공")
    else:
        print(f"❌ 텔레그램 메시지 전송 실패: {response.status_code}")

# ===== [4] 실행 함수 =====
def run():
    print(f"📅 [{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 뉴스 수집 시작")
    # 장애+지역 키워드 모두로 뉴스 수집
    all_keywords = REGIONS + FAULTS
    news = crawl_naver_news(all_keywords)
    # AND 조건 필터링
    filtered_news = filter_news_and(news, REGIONS, FAULTS)
    if filtered_news:
        message = f"📰 오늘의 뉴스 요약 ({len(filtered_news)}건):\n\n" + "\n\n".join(filtered_news)
        send_telegram_message(message, TOKEN, CHAT_ID)
    else:
        print("📭 수집된 뉴스가 없습니다.")

# ===== [5] 실행 =====
if __name__ == "__main__":
    run()